title = 'Coronium GS Client'
project = 'Coronium GS Client'
description = 'Coronium GS Client Docs'
full_description = 'A Corona SDK game client for Coronium GS'
format = 'markdown'
file = '../gs'
boilerplate = true
examples = { 'examples' }
topics = { 'license.md', 'readme.md', 'development.md' }
sort = true
template = "."
style = "."
not_luadoc = true
tparam_alias('player','Client')
tparam_alias('client', 'Client')
tparam_alias('tab', 'table')
